### ISSUE TITLE
Member reordering during source regeneration

### ISSUE THREAD

**Issue by n9** [Saltarelle/SaltarelleWeb#13]
After I have regenerated the C# source from WebIDL, [the commit](https://github.com/n9/SaltarelleWeb/commit/0fd0a7bdcf25089fd3f9f57f30cb42325e5a3f93) contains lot of changes caused by member reordering. It seems to be caused by locale dependent ordering.

**Comment by erik-kallen** [comment]
I can't explain this. Are you using .net or mono? I doubt it is a culture thing, because it would be a very strange culture that sorts letters completely different to my culture (sv-SE, which should be identical to en-US for these characters).

**Comment by n9** [comment]
I am using .NET, `cs-CZ` culture where unfortunately `'ch'` from some legacy reasons (linguists would kill me:o) is considered as a single character which is located after `'h'`. (I think it is because of pronunciation.)

Therefore, I think the generator is using `CurrentCulture` for string comparison / sorting. I think it would be better to use `CultureInvariant`.

**Comment by erik-kallen** [comment]
Should be fixed now
