### ISSUE TITLE
WebGL unsigned long issue

### ISSUE THREAD

**Issue by n9** [Saltarelle/SaltarelleWeb#14]
Some WebGL code needs casting int/uint casting, for instance:

``` C#
gl.TexParameteri(WebGLRenderingContext.TEXTURE_2D, WebGLRenderingContext.TEXTURE_WRAP_S, WebGLRenderingContext.CLAMP_TO_EDGE);
```

Since `WebGLRenderingContext` contains method with the last parameter of type `int`:

``` C#
// IDL: void texParameteri(GLenum target, GLenum pname, GLint param); 
public void TexParameteri(uint target, uint pname, int param);
```

and `uint` constant:

``` C#
// IDL: const GLenum CLAMP_TO_EDGE                  = 0x812F;
public const uint CLAMP_TO_EDGE = 33071;
```

The problem is caused because `GLenum` is defined in IDL as:

``` IDL
typedef unsigned long  GLenum;
```

There are more cases of casting problem in the spec, e.g. `Uniform1i` vs. `TEXTURE_2D`.

One possible workaround is to define alternative methods, such as:

``` C#
public void TexParameteri(uint target, uint pname, uint param) { }
public void Uniform1i(WebGLUniformLocation location, uint x) { }
```

However similar problem is with:

``` IDL
GLint getAttribLocation(WebGLProgram? program, DOMString name)
```

vs.

``` IDL
void enableVertexAttribArray(GLuint index)
```

from [WebGL specification](http://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.10).

I think that the spec considers `unsigned long` as non-negative integer _implicitly convertible_ to common integer `long`.

So, the solution from my point of view is to translate IDL's `unsigned long` to C#'s `int`.

**Comment by erik-kallen** [comment]
I made this change in 88f5351e278a6cb3053b7b03290b52e6ad219a76

**Comment by n9** [comment]
Looks ok, thx.
