### ISSUE TITLE
System.Html.Event.Data and Source are missing

### ISSUE THREAD

**Issue by jdluzen** [Saltarelle/SaltarelleWeb#9]
As the title says, System.Html.Event.Data and Source are missing. These are used with AddEventListener and PostMessage. There may be more, not sure.

**Comment by erik-kallen** [comment]
I can't find any information about these members either at [W3C](http://www.w3.org/TR/DOM-Level-2-Events/events.html) or [MDN](https://developer.mozilla.org/en/docs/Web/API/Event). Can you elaborate?

**Comment by jdluzen** [comment]
It appears that it's a draft right now, but widely supported: http://en.wikipedia.org/wiki/Web_Messaging. I ran across it because I need Knockout in a Chrome Packaged App, but it doesn't support eval without sandboxing, which means I need to pass messages across using PostMessage and friends.

More info here: https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage

**Comment by erik-kallen** [comment]
These members exist on `MessageEvent`.

**Comment by jdluzen** [comment]
Great, thanks!
